# Generated by Django 3.2.6 on 2021-10-10 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and Unique', max_length=255, unique=True, verbose_name='BudgetCode  Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='BudgetCode Slug')),
                ('digits7', models.IntegerField()),
                ('heading', models.CharField(max_length=255)),
                ('vrsHead', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'BudgetCode',
                'verbose_name_plural': 'BudgetCodes',
            },
        ),
        migrations.CreateModel(
            name='Consumerunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('parent_office', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Consumer Unit Name',
                'verbose_name_plural': 'Consumer Unit Names',
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_cheque', models.BooleanField(default=True)),
                ('taxrate', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Income TAX Rate')),
                ('taxamount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Income TAX Aomount')),
                ('vatrate', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='VAT Rate')),
                ('vatamount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='VAT Amount')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('checked_by', models.CharField(default='Abdur Rahman', help_text='Required', max_length=255, verbose_name='Checked BY Whom')),
                ('consunit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='budget.consumerunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expcode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alt_exp', to='budget.category')),
            ],
            options={
                'verbose_name': 'Expenditure',
                'verbose_name_plural': 'Expenditures',
            },
        ),
        migrations.CreateModel(
            name='Procurementprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('tin_no', models.CharField(max_length=13)),
                ('vat_no', models.CharField(max_length=13)),
                ('is_registered', models.BooleanField(default=True)),
                ('reg_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Procurement Provider Name',
                'verbose_name_plural': 'Procurement Provider Names',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=30)),
                ('invoice_date', models.DateField()),
                ('rv_no', models.CharField(max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='budget.expenditure')),
            ],
            options={
                'verbose_name': 'Invoice Detail',
                'verbose_name_plural': 'Invoice Details',
            },
        ),
        migrations.AddField(
            model_name='expenditure',
            name='itemsupplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='budget.procurementprovider'),
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('allotedon', models.DateField()),
                ('altauth', models.CharField(default='23.03.2600.039.51.001.21.000/    A', max_length=70)),
                ('altamount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('altcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='budget.category')),
                ('altunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.consumerunit')),
            ],
            options={
                'verbose_name': 'Allotment',
                'verbose_name_plural': 'Allotment',
                'ordering': ('altcode',),
            },
        ),
    ]
