# Generated by Django 3.2.6 on 2021-10-12 16:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='allotedon',
            field=models.DateField(verbose_name='Allotment Date'),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='altamount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Alloted Amount '),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='altauth',
            field=models.CharField(default='23.03.2600.039.51.001.21.000/    A', max_length=70, verbose_name='Vide Ltr Reference'),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='altcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='budget.category', verbose_name='Budget Codes'),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='altunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.consumerunit', verbose_name='For Which Office'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='consunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='budget.consumerunit', verbose_name='Consumer Office Name'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='expcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alt_exp', to='budget.category', verbose_name='Budget Codes'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='itemsupplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='budget.procurementprovider', verbose_name='Select Your Supplier'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='updated_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Approved Date'),
        ),
    ]
