# Generated by Django 3.2.6 on 2022-04-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20211227_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inv_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='taxamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Income TAX Amount'),
        ),
    ]
